color0 #15121a
color1 #ffb4ab
color2 #d1bcff
color3 #d0bdf9
color4 #fface7
color5 #d1bcff
color6 #d0bdf9
color7 #e7e0ec
color8 #958e9f
color9 #ffb4ab
color10 #d1bcff
color11 #d0bdf9
color12 #fface7
color13 #d1bcff
color14 #d0bdf9
color15 #e7e0ec

cursor                #e7e0ec
cursor_text_color     #15121a
background            #15121a
foreground            #e7e0ec
selection_foreground  #cbc3d5
selection_background  #4a4453
active_border_color   #d1bcff
inactive_border_color #4a4453
url_color             #d1bcff

active_tab_foreground   #3d008f
active_tab_background   #d1bcff
inactive_tab_foreground #cbc3d5
inactive_tab_background #4a4453
cursor_trail_color      #cbc3d5
