[colors.primary]
background = '#121416'
foreground = '#e2e2e5'
 
[colors.cursor]
text = '#e2e2e5'
cursor = '#c2c7cf' 
 
[colors.vi_mode_cursor]
text = '#121416'
cursor = '#97cbff' 
 
[colors.search.matches]
foreground = '#42474e' 
background = '#d3bfe6' 
 
[colors.search.focused_match]
foreground = '#42474e' 
background = '#97cbff' 
 
[colors.footer_bar]
foreground = '#42474e' 
background = '#e2e2e5' 
 
[colors.hints.start]
foreground = '#42474e' 
background = '#b9c8da' 
 
[colors.hints.end]
foreground = '#42474e' 
background = '#b9c8da' 
 
[colors.selection]
text = '#121416'
background = '#97cbff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#97cbff' 
yellow = '#00639b' 
blue = '#97cbff' 
magenta = '#d3bfe6' 
cyan = '#b9c8da' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 